
(function(){
  const qs=(s,r=document)=>r.querySelector(s), qsa=(s,r=document)=>[...r.querySelectorAll(s)];
  window.qrToast=function(message,type='success'){let stack=qs('.toast-stack');if(!stack){stack=document.createElement('div');stack.className='toast-stack';document.body.appendChild(stack)}const el=document.createElement('div');el.className='qr-toast '+type;el.textContent=message;stack.appendChild(el);setTimeout(()=>el.remove(),3200)};
  function tools(){if(qs('.floating-tools'))return;document.body.insertAdjacentHTML('beforeend',`<div class="floating-tools"><button id="themeToggle" title="Dark mode" aria-label="Toggle dark mode">◐</button><a class="whatsapp" href="https://wa.me/970567147697" target="_blank" rel="noopener" title="WhatsApp" aria-label="Contact QR Motors on WhatsApp">✆</a><button id="scrollTop" title="Back to top" aria-label="Back to top">↑</button></div>`);qs('#themeToggle').onclick=()=>{document.body.classList.toggle('dark-mode');localStorage.setItem('qrDark',document.body.classList.contains('dark-mode'))};qs('#scrollTop').onclick=()=>scrollTo({top:0,behavior:'smooth'});if(localStorage.getItem('qrDark')==='true')document.body.classList.add('dark-mode')}

  function cleanNavigation(){
    const header=qs('header'), nav=header&&qs('nav',header);
    if(!header||!nav||qs('.mobile-menu-button',header))return;
    const btn=document.createElement('button');
    btn.className='mobile-menu-button'; btn.type='button'; btn.setAttribute('aria-label','Open navigation'); btn.textContent='☰';
    header.insertBefore(btn,nav);
    btn.addEventListener('click',()=>{nav.classList.toggle('menu-open');btn.textContent=nav.classList.contains('menu-open')?'×':'☰'});
    qsa('a',nav).forEach(a=>a.addEventListener('click',()=>nav.classList.remove('menu-open')));
  }

  function richFooter(){const f=qs('footer');if(!f||f.classList.contains('rich-footer'))return;f.className='rich-footer';f.innerHTML=`<div class="rich-footer-grid"><div><h2>QR Motors</h2><p>A modern student-built automotive marketplace for discovering, comparing and requesting cars with confidence.</p></div><div><h4>Explore</h4><a href="cars.html">Cars</a><a href="compare.html">Compare</a><a href="dealers.html">Showroom</a></div><div><h4>Support</h4><a href="tips.html">Buying Guide</a><a href="contact.html">Contact</a><a href="about.html">About Project</a></div><div><h4>Showroom</h4><p>Nablus, Palestine</p><p>Sat–Thu · 9:00–18:00</p><p>info@qrmotors.local</p></div></div><div class="rich-footer-bottom"><span>© 2026 QR Motors</span><span>Frontend student project · HTML · CSS · JavaScript</span></div>`}
  function decorateCards(){qsa('.car-card').forEach((card,i)=>{if(qs('.badge-row',card))return;const name=qs('h3',card)?.textContent||'';let badge=i%4===0?'Featured':i%4===1?'Best Deal':i%4===2?'New':'Verified';card.insertAdjacentHTML('afterbegin',`<div class="badge-row"><span class="car-badge">${badge}</span>${/Tesla|Electric/i.test(name)?'<span class="car-badge dark">Electric</span>':''}</div>`)});}
  function carsTools(){const container=qs('#carsGrid, .cars-page .car-container, .catalog-section .car-container');if(!container||qs('.toolbar-upgrade'))return;container.insertAdjacentHTML('beforebegin',`<div class="toolbar-upgrade"><button class="active" data-view="grid">▦ Grid</button><button data-view="list">☰ List</button><button onclick="location.href='cars.html?fuel=Electric'">⚡ Electric</button><button onclick="location.href='cars.html?category=Luxury'">◆ Luxury</button><button onclick="location.href='compare.html'">⇄ Compare</button></div>`);qsa('[data-view]').forEach(b=>b.onclick=()=>{qsa('[data-view]').forEach(x=>x.classList.remove('active'));b.classList.add('active');container.classList.toggle('list-view',b.dataset.view==='list')})}
  function finance(){if(!qs('#financeCalculator'))return;const calc=()=>{const price=+qs('#finPrice').value||0,down=+qs('#finDown').value||0,months=+qs('#finMonths').value||36,annual=+qs('#finRate').value||5.5;const principal=Math.max(0,price-down),r=annual/1200;const pay=r?principal*r*Math.pow(1+r,months)/(Math.pow(1+r,months)-1):principal/months;qs('#monthlyPayment').textContent=Math.round(pay).toLocaleString()+' NIS'};qsa('#financeCalculator input,#financeCalculator select').forEach(x=>x.addEventListener('input',calc));calc()}
  function dashboard(){const root=qs('#userDashboardRoot,#adminDashboardRoot');if(!root||qs('.dashboard-banner',root))return;const user=JSON.parse(localStorage.getItem('currentUser')||'null');const name=user?.username||'Guest';root.insertAdjacentHTML('afterbegin',`<div class="dashboard-banner"><div class="profile-panel"><div class="profile-avatar">${name.charAt(0).toUpperCase()}</div><h2>${name}</h2><p class="premium-subtitle">Manage requests, favorites and recent activity from one place.</p><div class="toolbar-upgrade"><a class="details-btn" href="cars.html">Browse cars</a><a class="details-btn" href="favorites.html">Saved cars</a></div></div><div class="dashboard-chart"><b>Weekly activity</b><div class="mini-bars"><span style="height:35%"></span><span style="height:62%"></span><span style="height:45%"></span><span style="height:85%"></span><span style="height:68%"></span><span style="height:95%"></span><span style="height:72%"></span></div></div></div>`)}
  document.addEventListener('DOMContentLoaded',()=>{cleanNavigation();tools();richFooter();decorateCards();carsTools();finance();dashboard();});
})();
